### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils'

### ISSUE THREAD

**Issue by teamarctix** [Kinuseka/GoGo-Downloader-R2#2]
(venv) PS C:\Users\lenovo\Desktop\animedl\GoGo-Downloader-R2> python rungogo.py
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\animedl\GoGo-Downloader-R2\rungogo.py", line 1, in <module>
    from processor import UrlFixer, UrlSearch, pagination_link, Get_ID, pretty_size, validatename, HlsObject, pick_quality
  File "C:\Users\lenovo\Desktop\animedl\GoGo-Downloader-R2\processor.py", line 4, in <module>
    from CFSession import cfSession, cfexception
  File "C:\Users\lenovo\Desktop\animedl\GoGo-Downloader-R2\venv\Lib\site-packages\CFSession\__init__.py", line 3, in <module>
    from .cf import CFBypass
  File "C:\Users\lenovo\Desktop\animedl\GoGo-Downloader-R2\venv\Lib\site-packages\CFSession\cf.py", line 7, in <module>
    import undetected_chromedriver as uc
  File "C:\Users\lenovo\Desktop\animedl\GoGo-Downloader-R2\venv\Lib\site-packages\undetected_chromedriver\__init__.py", line 44, in <module>
    from .patcher import IS_POSIX
  File "C:\Users\lenovo\Desktop\animedl\GoGo-Downloader-R2\venv\Lib\site-packages\undetected_chromedriver\patcher.py", line 4, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'

> how to install distutils? 

i have already try this but getting this error
(venv) PS C:\Users\lenovo\Desktop\animedl\GoGo-Downloader-R2> pip install distutils
ERROR: Could not find a version that satisfies the requirement distutils (from versions: none)
ERROR: No matching distribution found for distutils

**Comment by Kinuseka** [comment]
Please try to keep issues on topic. This error is unrelated to GoGo-Downloader-R2

Upon doing simple google research: "no module distutils" 
Demonstration: https://googlethatforyou.com?q=no%20module%20distutils

We find that there are many results that provided solutions PLEASE do your own due diligence before opening an issue like these
