### ISSUE TITLE
Downloading recently released anime will cause index error

### ISSUE THREAD

**Issue by Kinuseka** [Kinuseka/GoGo-Downloader-R2#4]
Goal: Find possible alternatives besides erroring out.

- [ ]  Is there an alternative quality?
- [ ]  Alternative sources?

If non fits in the above then

- [ ] Catch the error and let the user know instead of an exception

**Comment by Kinuseka** [comment]
```
Traceback (most recent call last):
  File "RunGoGo.py", line 243, in <module>
    main()
  File "RunGoGo.py", line 226, in main
    return ResultZone("Home")
  File "RunGoGo.py", line 204, in ResultZone
    return Home_UI(config.get_host)
  File "RunGoGo.py", line 198, in Home_UI
    return Download_UI(new_url, result_title[selection-1]['title_name'], result_title[selection-1]['episode'])#This needs to go straight to Downloader or Video Scraper
  File "RunGoGo.py", line 105, in Download_UI
    video = pick_quality(video_data, preferred_quality=config.video_quality_preference)
  File "processor.py", line 96, in pick_quality
    return qualities[0]
IndexError: list index out of range
```
